from tkinter import *
#take authenticate first without it not anything possible
root=Tk()
root.title("Calculator")
root.geometry("800x500")
def add():
    num1=e1.get()
    num2=e2.get()
    label3.config(text=f"Total  = {int(num1)+int(num2)}")
def sub():
    num1=e1.get()
    num2=e2.get()
    label4.config(text=f"Total  = {int(num1)-int(num2)}")
def mul():
    num1=e1.get()
    num2=e2.get()
    label5.config(text=f"Total  = {int(num1)*int(num2)}")
def div():
    num1=e1.get()
    num2=e2.get()
    label6.config(text=f"Total  = {int(num1)/int(num2):.2f}")
label1=Label(root,text="Enter Number1 = ")
label1.place(x=50,y=10)
label2=Label(root,text="Enter Number2 = ")
label2.place(x=50,y=30)
label3=Label(root,text="")
label3.place(x=50,y=50)
e1=Entry(root)
e1.place(x=200,y=10)
e2=Entry(root)
e2.place(x=200,y=35)
button1=Button(root,width=10,text="EXIT",command=root.destroy)
button1.place(x=270,y=120)
button=Button(root,width=10,text="Addtion",command=add)
button.place(x=60,y=70)
label4=Label(root,text="")
label4.place(x=50,y=50)
button2=Button(root,width=10,text="Subtraction",command=sub)
button2.place(x=200,y=70)
label5=Label(root,text="")
label5.place(x=50,y=50)
button3=Button(root,width=10,text="Multiplication",command=mul)
button3.place(x=340,y=70)
label6=Label(root,text="")
label6.place(x=50,y=50)
button4=Button(root,width=10,text="Division",command=div)
button4.place(x=480,y=70)
mainloop()
